spring:
  application:
    name: wrm
  datasource:
    url: jdbc:postgresql://localhost:5432/wrm_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true

  profiles:
    active: prod