spring:
  application:
    name: Waiting room
  datasource:
    url: jdbc:postgresql://localhost:5432/wrm
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect